import type { NextPage } from "next";
import {
  Card,
  Text,
  Container,
  Row,
  Input,
  Button,
  Modal,
} from "@nextui-org/react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { KeyboardEvent, useState } from "react";
import { FormElement } from "@nextui-org/react/types/input";
import List from "../components/Table";

interface Cart {
  id: number;
  price: number;
  name: string;
  quantity: number;
}

const list = [
  {
    id: 1,
    price: 14.5,
    name: "Banana",
    quantity: 1,
  },
  {
    id: 2,
    price: 2.99,
    name: "Cookies",
    quantity: 1,
  },
  {
    id: 3,
    price: 1.74,
    name: "Leite",
    quantity: 1,
  },
  {
    id: 4,
    price: 3.5,
    name: "Limão",
    quantity: 1,
  },
  {
    id: 5,
    price: 8.99,
    name: "Frango",
    quantity: 1,
  },
  {
    id: 6,
    price: 13.25,
    name: "Alface",
    quantity: 1,
  },
];

const Home: NextPage = () => {
  const [visible, setVisible] = useState(false);
  const handler = () => setVisible(true);
  const closeHandler = () => {
    setVisible(false);
  };

  const [cart, setCart] = useState<Cart[]>([]);
  const [item, setItem] = useState("");
  const [receivedInput, setReicivedInput] = useState("");
  const [received, setReicived] = useState(0);

  function removeItem(index: number) {
    let aux: Cart[] = [];
    cart.forEach((element) => {
      if (element.id !== index) {
        aux.push(element);
      }
    });
    setCart(aux);
  }
  function resetCalculator() {
    setCart([]);
    setItem("");
    setReicivedInput("");
    setReicived(0);
    closeHandler();
  }

  function handleKeyPress(event: KeyboardEvent<FormElement>) {
    const aux = cart;

    if (event.key === "Enter") {
      const found = aux.some((element) => element.id === Number(item));

      if (found) {
        aux.forEach((element) => {
          if (element.id === Number(item)) {
            element.quantity = element.quantity + 1;
          }
        });
      } else {
        list.forEach((element) => {
          if (element.id === Number(item)) {
            aux.push(element);
          }
        });
      }

      setCart(aux);
      setItem("");
    }
  }

  var sum = cart.reduce(function (accumulator, object) {
    return accumulator + object.quantity * object.price;
  }, 0);
  var sumItens = cart.reduce(function (accumulator, object) {
    return accumulator + object.quantity;
  }, 0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Calculadora de Troco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container xs>
          <Row justify="center" align="center">
            <Text
              h1
              color="white"
              css={{
                textGradient: "45deg, $blue600 -20%, $pink600 50%",
              }}
              weight="bold"
            >
              Calculadora de Troco
            </Text>
          </Row>

          <Card css={{ padding: "1rem" }}>
            <Card.Body css={{ padding: "2rem", gap: "1rem" }}>
              <Input
                clearable
                underlined
                labelPlaceholder="Digite o código do produto"
                id="one"
                value={item}
                onChange={(e) => {
                  setItem(e.target.value);
                }}
                onKeyPress={(event) => {
                  handleKeyPress(event);
                }}
              />

              {cart.length > 0 && <List cart={cart} removeItem={removeItem} />}
              <Card>
                <Card.Body css={{ padding: "1rem", gap: 4 }}>
                  <Container
                    css={{
                      justifyContent: "space-between",
                      d: "flex",
                      w: "100%",
                    }}
                  >
                    <div>
                      <Text css={{ m: 0 }}>
                        <strong>ITENS: </strong> {sumItens}
                      </Text>
                      <Text css={{ m: 0 }}>
                        <strong>SUBTOTAL: </strong>
                        {sum.toLocaleString("pt-br", {
                          style: "currency",
                          currency: "BRL",
                        })}
                      </Text>
                    </div>

                    <div>
                      <Button
                        auto
                        color="secondary"
                        shadow
                        onPress={() => setVisible(true)}
                      >
                        PAGAR
                      </Button>
                      <Modal
                        closeButton
                        blur
                        aria-labelledby="modal-title"
                        open={visible}
                        onClose={closeHandler}
                      >
                        <Modal.Header>
                          <Text id="modal-title" size={18}>
                            CALCULAR TROCO
                          </Text>
                        </Modal.Header>
                        <Modal.Body>
                          <Input
                            step={0.2}
                            onChange={(e) => {
                              setReicivedInput(e.target.value);
                            }}
                            fullWidth
                            size="lg"
                            label="Valor á receber"
                            placeholder="00.00"
                            type="number"
                          />
                          <Button
                            auto
                            color="secondary"
                            shadow
                            onPress={() => {
                              setReicived(Number(receivedInput));
                            }}
                          >
                            PAGAR
                          </Button>
                          <Text css={{ m: 0 }}>
                            <strong>SUBTOTAL: </strong>
                            {sum.toLocaleString("pt-br", {
                              style: "currency",
                              currency: "BRL",
                            })}
                          </Text>
                          <Text css={{ m: 0 }}>
                            <strong>TOTAL PAGO: </strong>
                            {received.toLocaleString("pt-br", {
                              style: "currency",
                              currency: "BRL",
                            })}
                          </Text>
                          {received && (
                            <Text css={{ m: 0 }}>
                              <strong>TROCO: </strong>
                              {(received - sum).toLocaleString("pt-br", {
                                style: "currency",
                                currency: "BRL",
                              })}
                            </Text>
                          )}
                        </Modal.Body>
                        <Modal.Footer>
                          <Button
                            auto
                            flat
                            color="warning"
                            onPress={closeHandler}
                          >
                            VOLTAR
                          </Button>
                          <Button
                            auto
                            flat
                            color="error"
                            onPress={resetCalculator}
                          >
                            TERMINAR
                          </Button>
                        </Modal.Footer>
                      </Modal>
                    </div>
                  </Container>
                </Card.Body>
              </Card>
            </Card.Body>
          </Card>
        </Container>
      </main>
    </div>
  );
};

export default Home;
